### ISSUE TITLE
Redraw bug with domvm's drainQueue()

### ISSUE THREAD

**Issue by jlgrall** [jlgrall/domvm-mobx#2]
@leeoniya The new redrawing algorithm that we discussed in issue https://github.com/domvm/domvm/issues/206 and which was implemented in release v3.4.7 of domvm, causes problems for domvm-mobx.

Lets say we have a view A which contains a view B which contains a view C. They are all rendering datas from a MobX store, so they can stall independently from one another.

If only view A is stale, the [`drainQueue()`](https://github.com/domvm/domvm/blob/master/src/view/ViewModel.js#L17) will redraw view A which will also redraw its children, that is view B. But domvm-mobx will prevent the redrawing of view B because it is not stale. Ok, this is expected an works well.

Now the problem comes if view A and C are stale, but not view B. Here is what happens: view A is redrawn, which also tries to redraw view B. But view B is not redrawn because domvm-mobx prevents it. Consequently, its children are not automatically redrawn. Now `drainQueue()` should redraw view C, but because it sees that view A, which is in the parent chain of view C, is also in the `redrawQueue` Set, it will skip it. At the end, view C is not redrawn, and this is a bug.

This is not a problem for normal domvm, only for domvm-mobx.

I am thinking of replacing the domvm `drainQueue()` from domvm-mobx with a custom one which would force redrawing of stale observer vm.

**Comment by leeoniya** [comment]
why not walk up the vtree here [1] and tag all ancestors' `vm.mobxObserver.stale = true`? this would allow B to be redrawn, yes? is it because you want avoid redrawing B at all costs?

EDIT: hmm, this might leave behind the stale flags or need more code to reset them and may need insight into the current queue to know how far up the tree to go.

the other, less sexy solution is expanding the API surface to expose an overridable logic behind queue management. i'm not a fan of this, TBH.

[1] https://github.com/domvm/domvm-mobx/blob/master/domvm-mobx.js#L91

**Comment by leeoniya** [comment]
i was thinking a bit more about this.

as far as what domvm can provide to facilitate this is the ability to force a redraw even if an ancestor is already in the queue. the rest you should be able to do within `domvm-mobx`. hopefully we can avoid exposing the queue itself (and insight into what's already queued is not necessary)

check out the last commit in the `force-redraw` branch [1] and let me know what you think.

[1] https://github.com/domvm/domvm/tree/force-redraw

**Comment by jlgrall** [comment]
Hi, thanks for your answers.

I took a look at your _force-redraw_ branch. But I see a number of problems with it. In the new `drainQueue()`, it forces the redrawing during the iteration of the `redrawQueue`, resulting in the same problems that were at the origin of the https://github.com/domvm/domvm/issues/206 report. More precisely, it would redraw forced children as many times as they have parents that are also redrawn. It would also sometimes redraw children before their parents, thus possibly using obsolete data or data that were removed because the child was expected to be removed by its parent.

After taking some time to think about my problem, for me, the simplest solution would be to execute the following `forceRedrawOfStaledObservers()` in `drainQueue()` just before `redrawQueue.clear()`:

```javascript
function forceRedrawOfStaledObservers(redrawQueue) {
    
    // We want to redraw the children after the parents, so we sort them by depth:
    var byDepth = [];
    
    redrawQueue.forEach(vm => {
        // Only keep staled domvm-mobx observers (and check they were not unmounted)
        if (vm.mobxObserver && vm.mobxObserver.stale && vm.node != null) {
            var depth = 0,
                parVm = vm;
            while (parVm = parVm.parent()) depth++;
            
            if (!byDepth[depth]) byDepth[depth] = [];
            byDepth[depth].push(vm);
        }
    });
    
    for (var d = 0; d < byDepth.length; d++) {
        if (byDepth[d]) {
            byDepth[d].forEach(vm => {
                // May have been redrawn by a parent in the meanwhile:
                if (vm.mobxObserver.stale && vm.node != null) vm.redraw(true);
            });
        }
    }
}
```

I can always rewrite `ViewModel.prototype.redraw()` from domvm-mobx, to add a call to my function in the rewritten `drainQueue()`, but I would rather find a better way.

I didn't know that you wanted to add a force-redraw ability, but from what I said at the beginning of this answer, I think you will probably need to redo your force-redraw. So I am thinking, as I am seeing that your force-redraw is similar to mine, maybe you could add a hook just before `redrawQueue.clear()`, where we could both add our own function call somehow ? Or maybe some other way to make both our force-redraw work at the same time ?

I still have another way to fix my problem if you don't want me to hook into `drainQueue()`:

```javascript
var redrawForcedQueue = new Set();
var rafForcedId = 0;

var domvmRedraw = domvm.ViewModel.prototype.redraw;
domvm.ViewModel.prototype.redraw = function(sync) {
    // Ensure the rafId is set before ours, so it should (?) execute before ours:
    domvmRedraw.call(this, sync);

    if (!sync) {
        if (this.mobxObserver) redrawForcedQueue.add(this);
        
        // Must be setup in the same conditions as domvm's raf, so that it executes just after it:
        if (rafForcedId === 0) rafForcedId = requestAnimationFrame(drainForcedQueue);
    }
};

function drainForcedQueue() {
    forceRedrawOfStaledObservers(redrawForcedQueue);
    redrawForcedQueue.clear();
    rafForcedId = 0;
}
```

Edit: fixed code after testing it in my project. It now works correctly.

**Comment by leeoniya** [comment]
good points.

> maybe you could add a hook just before `redrawQueue.clear()`

yeah, that sounds ok. how about:

```js
domvm.cfg({
  didRedraw: function(redrawQueue) {
    // ...
  }
});
```

while i like the naming uniformity/conciseness, `did*` *hooks* in domvm are designed to fire after a repaint, so should probably pick another name? maybe `rafRedraws`, `rafRedraw`, `rafRedrawn`, `allRedrawn`, `multiRedraw`.

`rafRedraws` conveys both that it is some kind of batch and that it's rAF-coalesced, though it doesnt quite convey past tense.

maybe i'm overthinking it and we can just use `didRedraw` or plural `didRedraws` (batch implication, without exposing internal impl via rAF, which may change in the future).

**Comment by jlgrall** [comment]
`didAsyncRedraw`, `didLazyRedraw` ?

> `did*` _hooks_ in domvm are designed to fire after a repaint

I did not know that, I thought _did/will_ only meant _before/after_ (as in _before/after_ mount) like in other libraries. I did not realize it was about the repaint. So I see nothing preventing you from using _did*_.

**Comment by leeoniya** [comment]
> I did not know that

yeah, there are a lot of cases when the user needs to ensure that the DOM is in a settled state, such as measuring sizes or forcing a class to be applied so a CSS transition/animation can start with the correct initial values. if there was no repaint between `will` and `did`, then the browser would coalesce all dom mutations and you'd just end up with whatever happened in `did` masking any prior mutations. the scoreboard demo could not work without a post-repaint *did*.

> So I see nothing preventing you from using did*.

alright, `didRedraws` will probably be okay. it's a pretty specialized thing anyhow that few will use.

[1] https://domvm.github.io/domvm/demos/playground/#scoreboard

**Comment by leeoniya** [comment]
alright, give it a whirl: https://github.com/domvm/domvm/commit/a79af7b69606285b8aaa58767dcc767e80279e32

**Comment by jlgrall** [comment]
Are you sure you want to implement it this way ?

The way to set up `didRedraws` is exclusive. For instance, there is no way to have both your _force-redraw_ and my domvm-mobx at the same time. Also, if anyone else wanted to hook into `didRedraws`, it would be very hard, defeating the purpose of allowing hooks in the first place.

If possible, I would rather there be a way to access the currently defined `didRedraws` so I could do something like this:
```javascript
var prevDidRedraw = domvm.config.didRedraw;
domvm.config.didRedraw = function(args) {
  prevDidRedraw(args);
  
  // My own code here...
};
```

This way my code wouldn't interfere with other code. I already do this when I hook into `vm.init()`, `vm.render()`, `vm.hooks.willUnmount()` and `vm.diff.eq` from domvm-mobx, even though I don't always do it in the same exact way.

**Comment by leeoniya** [comment]
> Also, if anyone else wanted to hook into `didRedraws`

let's wait and see if anyone actually needs this first. FWIW, i did not personally have a need/plan for forced redraw and only proposed it as one potential solution to this issue.

if we decide to make the config accessible, i'd rather have `domvm.cfg()` (without a value) return the current config, eg `{onemit, syncRedraw, didRedraws...}` so they can be wrapped and re-set as needed. i dont want to expose them as overloadable properties since this removes a useful [to me] layer of abstraction and increases the BC commitment surface.
