### ISSUE TITLE
Demo for playground

### ISSUE THREAD

**Issue by jlgrall** [jlgrall/domvm-mobx#3]
Hi @leeoniya

I have been toying with a demo for the playground. I put everything into a single HTML file so you can easily try it. What do you think ?

domvm-mobx-demo.html: https://gist.github.com/jlgrall/0e3194fe5e17e423c225dc10c2bd00c6

**Comment by leeoniya** [comment]
thanks for putting that together. i reformatted it a bit and it's live at:

https://domvm.github.io/domvm/demos/playground/#mobx

**Comment by jlgrall** [comment]
Ok, I did not expect that so soon, but I tried it and it works well.

I still want to change how the name of the observers are defined to improve debugging, so I will submit a PR later.

Also I though maybe the right side result panel is not very clear and not very easy to understand at first, so maybe I will improve that a bit.

**Comment by leeoniya** [comment]
> I still want to change how the name of the observers are defined to improve debugging, so I will submit a PR later.

sounds good. also `becomeStale` -> `becameStale` ;)

> Also I though maybe the right side result panel is not very clear and not very easy to understand

it looks clear enough to me but do as you please.

**Comment by jlgrall** [comment]
> also `becomeStale` -> `becameStale` ;)

Sorry, I did not understand, is there an instance of `becomeStale` that I forgot to change ?

**Comment by leeoniya** [comment]
oops, i missed that you've already changed it.

**Comment by jlgrall** [comment]
Actually, how do you want me to update the demo? Fork domvm and then make a PR? Directly commit to your domvm repo?

**Comment by leeoniya** [comment]
fork & pr please 🙏

**Comment by jlgrall** [comment]
Ok, sorry, I wrongly thought you gave me the rights to write to the domvm repo, which confused me because I didn't really wanted to. I will fork and PR. I am still not used to github organizations :-)

**Comment by jlgrall** [comment]
I want to add a comment at the start of the file `domvm/demos/lib/mobx.umd.min.js` with the MobX version, otherwise I will forget what it is. Do you agree ? Something like:

```javascript
// MobX 5.9.0 (https://github.com/mobxjs/mobx)
// Source: (https://cdnjs.com/libraries/mobx) use "mobx.umd.min.js" version
```

**Comment by leeoniya** [comment]
sure

**Comment by jlgrall** [comment]
What I like with your playground, is that it is easy to change the MobX script src to `https://cdnjs.cloudflare.com/ajax/libs/mobx/5.9.0/mobx.umd.js` or to other versions!

**Comment by leeoniya** [comment]
yep, i was always a fan of doing obvious in-html `<script>` includes in jsfiddle rather than choosing some buried toggle or libs & versions selector. seems like a lot of unnecessary abstraction for a code editor app. i also like the way sublime & vscode settings are just searchable, editable json files.
